# 1. Deshabilitar autoconfiguración de base de datos para arrancar el Swagger
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# 2. Asegurar que SpringDoc y Swagger levanten sí o sí
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# 3. Quitar cualquier rastro de H2 o MySQL conflictivo
spring.jpa.hibernate.ddl-auto=none
