# Spring Application Name
spring.application.name=backend

# Default to development when no explicit profile is provided.
# spring.profiles.default=dev

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.kipu.backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
application.jwt.secret=4S3cReTK1puB4ck3ndS3cur1tyK3yTh4tIsSuFf1c13ntlyL0ng4ndStr0ng!
application.jwt.expiration-ms=86400000

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false

# In-Memory Database Configuration for Agile Development
spring.datasource.url=jdbc:h2:mem:kipudb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable the H2 web console to check user tables
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# SMTP Gmail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pircaindustries@gmail.com
spring.mail.password=gpfk frxq aioc xriu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
